apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.12.0
directories:
  - path: config/upstream
    contents:
      - path: .
        githubRelease:
          slug: pivotal/kpack
          tag: v0.5.0
          assetNames: ["release-*.yaml"]
