#@ load("@ytt:data", "data")

#@ if data.values.ca_cert_data != "":
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-data
  namespace: kpack
stringData:
  type: ca-certificates
  ca-cert.pem: #@ data.values.ca_cert_data
#@ end

